-- AlterTable
ALTER TABLE "Leave" ALTER COLUMN "reason" DROP DEFAULT,
ALTER COLUMN "endDate" DROP DEFAULT,
ALTER COLUMN "leaveType" DROP DEFAULT,
ALTER COLUMN "startDate" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
